language: python
python: 2.7
cache:
  pip: true
  directories:
    - opencv/build
install:
  - sudo apt-get install python-dev python-numpy
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - ls
  - ls opencv
  - ls opencv/build
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j8
  - sudo make install
  - cd ../../
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/site-packages/
  - ls
  - ls opencv
  - ls opencv/build
script:
  - flake8 --statistics --show-source --disable-noqa
  - python run.py -i tests/images/goal2016.png
  - python run.py -i tests/images/goal2017.png
